# Generated by Django 3.0.5 on 2020-04-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Padidos',
            new_name='Pedidos',
        ),
    ]
